# Dependencies
markdown:         kramdown

# Setup
title:            Elm Narrative Engine dev-blog
tagline:          
  The winding path behind building an interactive story framework 
description: >
  The winding path behind building an interactive story-telling framework 
url:             ''
baseurl:          '/ene-dev'
permalink: pretty

excerpt_separator: <!--more-->

author:
  name:           Jeff Schomay
  url:            https://twitter.com/jschomay

paginate:         5

github:
  repo:           https://github.com/jschomay/elm-narrative-engine
